CREATE TABLE IF NOT EXISTS country_codes (
    id SMALLINT NOT NULL,
    code VARCHAR(2) NOT NULL,
    country VARCHAR(52) NOT NULL
    PRIMARY KEY (id)
);

INSERT INTO country_codes(id, code, country) VALUES (20, 'AD', 'Andorra');
INSERT INTO country_codes(id, code, country) VALUES (784, 'AE', 'United Arab Emirates');
INSERT INTO country_codes(id, code, country) VALUES (28, 'AG', 'Antigua and Barbuda');
INSERT INTO country_codes(id, code, country) VALUES (660, 'AI', 'Anguilla');
INSERT INTO country_codes(id, code, country) VALUES (8, 'AL', 'Albania');
INSERT INTO country_codes(id, code, country) VALUES (51, 'AM', 'Armenia');
INSERT INTO country_codes(id, code, country) VALUES (24, 'AO', 'Angola');
INSERT INTO country_codes(id, code, country) VALUES (10, 'AQ', 'Antarctica');
INSERT INTO country_codes(id, code, country) VALUES (32, 'AR', 'Argentina');
INSERT INTO country_codes(id, code, country) VALUES (16, 'AS', 'American Samoa');
INSERT INTO country_codes(id, code, country) VALUES (40, 'AT', 'Austria');
INSERT INTO country_codes(id, code, country) VALUES (36, 'AU', 'Australia');
INSERT INTO country_codes(id, code, country) VALUES (533, 'AW', 'Aruba');
INSERT INTO country_codes(id, code, country) VALUES (248, 'AX', 'Åland Islands');
INSERT INTO country_codes(id, code, country) VALUES (31, 'AZ', 'Azerbaijan');
INSERT INTO country_codes(id, code, country) VALUES (70, 'BA', 'Bosnia and Herzegovina');
INSERT INTO country_codes(id, code, country) VALUES (52, 'BB', 'Barbados');
INSERT INTO country_codes(id, code, country) VALUES (50, 'BD', 'Bangladesh');
INSERT INTO country_codes(id, code, country) VALUES (56, 'BE', 'Belgium');
INSERT INTO country_codes(id, code, country) VALUES (854, 'BF', 'Burkina Faso');
INSERT INTO country_codes(id, code, country) VALUES (100, 'BG', 'Bulgaria');
INSERT INTO country_codes(id, code, country) VALUES (48, 'BH', 'Bahrain');
INSERT INTO country_codes(id, code, country) VALUES (108, 'BI', 'Burundi');
INSERT INTO country_codes(id, code, country) VALUES (204, 'BJ', 'Benin');
INSERT INTO country_codes(id, code, country) VALUES (204, 'BJ', 'Saint Barthélemy');
INSERT INTO country_codes(id, code, country) VALUES (60, 'BM', 'Bermuda');
INSERT INTO country_codes(id, code, country) VALUES (96, 'BN', 'Brunei Darussalam');
INSERT INTO country_codes(id, code, country) VALUES (68, 'BO', 'Bolivia, Plurinational State of');
INSERT INTO country_codes(id, code, country) VALUES (535, 'BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO country_codes(id, code, country) VALUES (76, 'BR', 'Brazil');
INSERT INTO country_codes(id, code, country) VALUES (44, 'BS', 'Bahamas');
INSERT INTO country_codes(id, code, country) VALUES (64, 'BT', 'Bhutan');
INSERT INTO country_codes(id, code, country) VALUES (74, 'BV', 'Bouvet Island');
INSERT INTO country_codes(id, code, country) VALUES (72, 'BW', 'Botswana');
INSERT INTO country_codes(id, code, country) VALUES (112, 'BY', 'Belarus');
INSERT INTO country_codes(id, code, country) VALUES (84, 'BZ', 'Belize');
INSERT INTO country_codes(id, code, country) VALUES (124, 'CA', 'Canada');
INSERT INTO country_codes(id, code, country) VALUES (166, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO country_codes(id, code, country) VALUES (180, 'CD', 'Congo, Democratic Republic of the');
INSERT INTO country_codes(id, code, country) VALUES (140, 'CF', 'Central African Republic');
INSERT INTO country_codes(id, code, country) VALUES (178, 'CG', 'Congo');
INSERT INTO country_codes(id, code, country) VALUES (756, 'CH', 'Switzerland');
INSERT INTO country_codes(id, code, country) VALUES (384, 'CI', 'Côte d''Ivoire');
INSERT INTO country_codes(id, code, country) VALUES (184, 'CK', 'Cook Islands');
INSERT INTO country_codes(id, code, country) VALUES (152, 'CL', 'Chile');
INSERT INTO country_codes(id, code, country) VALUES (120, 'CM', 'Cameroon');
INSERT INTO country_codes(id, code, country) VALUES (156, 'CN', 'China');
INSERT INTO country_codes(id, code, country) VALUES (170, 'CO', 'Colombia');
INSERT INTO country_codes(id, code, country) VALUES (188, 'CR', 'Costa Rica');
INSERT INTO country_codes(id, code, country) VALUES (192, 'CU', 'Cuba');
INSERT INTO country_codes(id, code, country) VALUES (132, 'CV', 'Cabo Verde');
INSERT INTO country_codes(id, code, country) VALUES (531, 'CW', 'Curaçao');
INSERT INTO country_codes(id, code, country) VALUES (162, 'CX', 'Christmas Island');
INSERT INTO country_codes(id, code, country) VALUES (196, 'CY', 'Cyprus');
INSERT INTO country_codes(id, code, country) VALUES (203, 'CZ', 'Czechia');
INSERT INTO country_codes(id, code, country) VALUES (276, 'DE', 'Germany');
INSERT INTO country_codes(id, code, country) VALUES (262, 'DJ', 'Djibouti');
INSERT INTO country_codes(id, code, country) VALUES (208, 'DK', 'Denmark');
INSERT INTO country_codes(id, code, country) VALUES (212, 'DM', 'Dominica');
INSERT INTO country_codes(id, code, country) VALUES (214, 'DO', 'Dominican Republic');
INSERT INTO country_codes(id, code, country) VALUES (12, 'DZ', 'Algeria');
INSERT INTO country_codes(id, code, country) VALUES (218, 'EC', 'Ecuador');
INSERT INTO country_codes(id, code, country) VALUES (233, 'EE', 'Estonia');
INSERT INTO country_codes(id, code, country) VALUES (818, 'EG', 'Egypt');
INSERT INTO country_codes(id, code, country) VALUES (732, 'EH', 'Western Sahara');
INSERT INTO country_codes(id, code, country) VALUES (232, 'ER', 'Eritrea');
INSERT INTO country_codes(id, code, country) VALUES (724, 'ES', 'Spain');
INSERT INTO country_codes(id, code, country) VALUES (231, 'ET', 'Ethiopia');
INSERT INTO country_codes(id, code, country) VALUES (246, 'FI', 'Finland');
INSERT INTO country_codes(id, code, country) VALUES (242, 'FI', 'Fiji');
INSERT INTO country_codes(id, code, country) VALUES (238, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO country_codes(id, code, country) VALUES (583, 'FM', 'Micronesia, Federated States of');
INSERT INTO country_codes(id, code, country) VALUES (234, 'FO', 'Faroe Islands');
INSERT INTO country_codes(id, code, country) VALUES (250, 'FR', 'France');
INSERT INTO country_codes(id, code, country) VALUES (266, 'GA', 'Gabon');
INSERT INTO country_codes(id, code, country) VALUES (826, 'GB', 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO country_codes(id, code, country) VALUES (308, 'GD', 'Grenada');
INSERT INTO country_codes(id, code, country) VALUES (268, 'GE', 'Georgia');
INSERT INTO country_codes(id, code, country) VALUES (254, 'GF', 'French Guiana');
INSERT INTO country_codes(id, code, country) VALUES (831, 'GG', 'Guernsey');
INSERT INTO country_codes(id, code, country) VALUES (288, 'GH', 'Ghana');
INSERT INTO country_codes(id, code, country) VALUES (292, 'GI', 'Gibraltar');
INSERT INTO country_codes(id, code, country) VALUES (304, 'GL', 'Greenland');
INSERT INTO country_codes(id, code, country) VALUES (270, 'GM', 'Gambia');
INSERT INTO country_codes(id, code, country) VALUES (324, 'GN', 'Guinea');
INSERT INTO country_codes(id, code, country) VALUES (312, 'GP', 'Guadeloupe');
INSERT INTO country_codes(id, code, country) VALUES (226, 'GQ', 'Equatorial Guinea');
INSERT INTO country_codes(id, code, country) VALUES (300, 'GR', 'Greece');
INSERT INTO country_codes(id, code, country) VALUES (239, 'GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO country_codes(id, code, country) VALUES (320, 'GT', 'Guatemala');
INSERT INTO country_codes(id, code, country) VALUES (316, 'GU', 'Guam');
INSERT INTO country_codes(id, code, country) VALUES (624, 'GW', 'Guinea-Bissau');
INSERT INTO country_codes(id, code, country) VALUES (328, 'GY', 'Guyana');
INSERT INTO country_codes(id, code, country) VALUES (344, 'HK', 'Hong Kong');
INSERT INTO country_codes(id, code, country) VALUES (334, 'HM', 'Heard Island and McDonald Islands');
INSERT INTO country_codes(id, code, country) VALUES (340, 'HN', 'Honduras');
INSERT INTO country_codes(id, code, country) VALUES (191, 'HR', 'Croatia');
INSERT INTO country_codes(id, code, country) VALUES (332, 'HT', 'Haiti');
INSERT INTO country_codes(id, code, country) VALUES (348, 'HU', 'Hungary');
INSERT INTO country_codes(id, code, country) VALUES (360, 'ID', 'Indonesia');
INSERT INTO country_codes(id, code, country) VALUES (372, 'IE', 'Ireland');
INSERT INTO country_codes(id, code, country) VALUES (376, 'IL', 'Israel');
INSERT INTO country_codes(id, code, country) VALUES (833, 'IM', 'Isle of Man');
INSERT INTO country_codes(id, code, country) VALUES (356, 'IN', 'India');
INSERT INTO country_codes(id, code, country) VALUES (86, 'IO', 'British Indian Ocean Territory');
INSERT INTO country_codes(id, code, country) VALUES (368, 'IQ', 'Iraq');
INSERT INTO country_codes(id, code, country) VALUES (364, 'IR', 'Iran, Islamic Republic of');
INSERT INTO country_codes(id, code, country) VALUES (352, 'IS', 'Iceland');
INSERT INTO country_codes(id, code, country) VALUES (380, 'IT', 'Italy');
INSERT INTO country_codes(id, code, country) VALUES (832, 'JE', 'Jersey');
INSERT INTO country_codes(id, code, country) VALUES (388, 'JM', 'Jamaica');
INSERT INTO country_codes(id, code, country) VALUES (400, 'JO', 'Jordan');
INSERT INTO country_codes(id, code, country) VALUES (392, 'JP', 'Japan');
INSERT INTO country_codes(id, code, country) VALUES (404, 'KE', 'Kenya');
INSERT INTO country_codes(id, code, country) VALUES (417, 'KG', 'Kyrgyzstan');
INSERT INTO country_codes(id, code, country) VALUES (116, 'KH', 'Cambodia');
INSERT INTO country_codes(id, code, country) VALUES (296, 'KI', 'Kiribati');
INSERT INTO country_codes(id, code, country) VALUES (174, 'KM', 'Comoros');
INSERT INTO country_codes(id, code, country) VALUES (659, 'KN', 'Saint Kitts and Nevis');
INSERT INTO country_codes(id, code, country) VALUES (408, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO country_codes(id, code, country) VALUES (410, 'KR', 'Korea, Republic of');
INSERT INTO country_codes(id, code, country) VALUES (414, 'KW', 'Kuwait');
INSERT INTO country_codes(id, code, country) VALUES (136, 'KY', 'Cayman Islands');
INSERT INTO country_codes(id, code, country) VALUES (398, 'KZ', 'Kazakhstan');
INSERT INTO country_codes(id, code, country) VALUES (418, 'LA', 'Lao People''s Democratic Republic');
INSERT INTO country_codes(id, code, country) VALUES (422, 'LB', 'Lebanon');
INSERT INTO country_codes(id, code, country) VALUES (662, 'LC', 'Saint Lucia');
INSERT INTO country_codes(id, code, country) VALUES (438, 'LI', 'Liechtenstein');
INSERT INTO country_codes(id, code, country) VALUES (144, 'LK', 'Sri Lanka');
INSERT INTO country_codes(id, code, country) VALUES (430, 'LR', 'Liberia');
INSERT INTO country_codes(id, code, country) VALUES (426, 'LS', 'Lesotho');
INSERT INTO country_codes(id, code, country) VALUES (440, 'LT', 'Lithuania');
INSERT INTO country_codes(id, code, country) VALUES (442, 'LU', 'Luxembourg');
INSERT INTO country_codes(id, code, country) VALUES (428, 'LV', 'Latvia');
INSERT INTO country_codes(id, code, country) VALUES (434, 'LY', 'Libya');
INSERT INTO country_codes(id, code, country) VALUES (504, 'MA', 'Morocco');
INSERT INTO country_codes(id, code, country) VALUES (492, 'MC', 'Monaco');
INSERT INTO country_codes(id, code, country) VALUES (498, 'MD', 'Moldova, Republic of');
INSERT INTO country_codes(id, code, country) VALUES (499, 'ME', 'Montenegro');
INSERT INTO country_codes(id, code, country) VALUES (663, 'MF', 'Saint Martin, (French part)');
INSERT INTO country_codes(id, code, country) VALUES (450, 'MG', 'Madagascar');
INSERT INTO country_codes(id, code, country) VALUES (584, 'MH', 'Marshall Islands');
INSERT INTO country_codes(id, code, country) VALUES (807, 'MK', 'North Macedonia');
INSERT INTO country_codes(id, code, country) VALUES (466, 'ML', 'Mali');
INSERT INTO country_codes(id, code, country) VALUES (104, 'MM', 'Myanmar');
INSERT INTO country_codes(id, code, country) VALUES (496, 'MN', 'Mongolia');
INSERT INTO country_codes(id, code, country) VALUES (446, 'MO', 'Macao');
INSERT INTO country_codes(id, code, country) VALUES (580, 'MP', 'Northern Mariana Islands');
INSERT INTO country_codes(id, code, country) VALUES (474, 'MQ', 'Martinique');
INSERT INTO country_codes(id, code, country) VALUES (478, 'MR', 'Mauritania');
INSERT INTO country_codes(id, code, country) VALUES (500, 'MS', 'Montserrat');
INSERT INTO country_codes(id, code, country) VALUES (470, 'MT', 'Malta');
INSERT INTO country_codes(id, code, country) VALUES (480, 'MU', 'Mauritius');
INSERT INTO country_codes(id, code, country) VALUES (462, 'MV', 'Maldives');
INSERT INTO country_codes(id, code, country) VALUES (454, 'MW', 'Malawi');
INSERT INTO country_codes(id, code, country) VALUES (484, 'MX', 'Mexico');
INSERT INTO country_codes(id, code, country) VALUES (458, 'MY', 'Malaysia');
INSERT INTO country_codes(id, code, country) VALUES (508, 'MZ', 'Mozambique');
INSERT INTO country_codes(id, code, country) VALUES (516, 'NA', 'Namibia');
INSERT INTO country_codes(id, code, country) VALUES (540, 'NC', 'New Caledonia');
INSERT INTO country_codes(id, code, country) VALUES (562, 'NE', 'Niger');
INSERT INTO country_codes(id, code, country) VALUES (574, 'NF', 'Norfolk Island');
INSERT INTO country_codes(id, code, country) VALUES (566, 'NG', 'Nigeria');
INSERT INTO country_codes(id, code, country) VALUES (558, 'NI', 'Nicaragua');
INSERT INTO country_codes(id, code, country) VALUES (528, 'NL', 'Netherlands');
INSERT INTO country_codes(id, code, country) VALUES (578, 'NO', 'Norway');
INSERT INTO country_codes(id, code, country) VALUES (524, 'NP', 'Nepal');
INSERT INTO country_codes(id, code, country) VALUES (520, 'NR', 'Nauru');
INSERT INTO country_codes(id, code, country) VALUES (570, 'NU', 'Niue');
INSERT INTO country_codes(id, code, country) VALUES (554, 'NZ', 'New Zealand');
INSERT INTO country_codes(id, code, country) VALUES (512, 'OM', 'Oman');
INSERT INTO country_codes(id, code, country) VALUES (591, 'PA', 'Panama');
INSERT INTO country_codes(id, code, country) VALUES (604, 'PE', 'Peru');
INSERT INTO country_codes(id, code, country) VALUES (258, 'PF', 'French Polynesia');
INSERT INTO country_codes(id, code, country) VALUES (598, 'PG', 'Papua New Guinea');
INSERT INTO country_codes(id, code, country) VALUES (608, 'PH', 'Philippines');
INSERT INTO country_codes(id, code, country) VALUES (586, 'PK', 'Pakistan');
INSERT INTO country_codes(id, code, country) VALUES (616, 'PL', 'Poland');
INSERT INTO country_codes(id, code, country) VALUES (666, 'PM', 'Saint Pierre and Miquelon');
INSERT INTO country_codes(id, code, country) VALUES (612, 'PN', 'Pitcairn');