CREATE TABLE IF NOT EXISTS two-letter_country_codes (
    id SMALLINT NOT NULL,
    code VARCHAR(2) NOT NULL,
    country VARCHAR(52) NOT NULL
    PRIMARY KEY (id)
);

INSERT INTO two-letter_country_codes(id, code, country) VALUES (20, 'AD', 'Andorra');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (784, 'AE', 'United Arab Emirates');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (28, 'AG', 'Antigua and Barbuda');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (660, 'AI', 'Anguilla');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (8, 'AL', 'Albania');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (51, 'AM', 'Armenia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (24, 'AO', 'Angola');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (10, 'AQ', 'Antarctica');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (32, 'AR', 'Argentina');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (16, 'AS', 'American Samoa');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (40, 'AT', 'Austria');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (36, 'AU', 'Australia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (533, 'AW', 'Aruba');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (248, 'AX', 'Åland Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (31, 'AZ', 'Azerbaijan');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (70, 'BA', 'Bosnia and Herzegovina');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (52, 'BB', 'Barbados');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (50, 'BD', 'Bangladesh');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (56, 'BE', 'Belgium');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (854, 'BF', 'Burkina Faso');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (100, 'BG', 'Bulgaria');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (48, 'BH', 'Bahrain');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (108, 'BI', 'Burundi');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (204, 'BJ', 'Benin');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (204, 'BJ', 'Saint Barthélemy');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (60, 'BM', 'Bermuda');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (96, 'BN', 'Brunei Darussalam');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (68, 'BO', 'Bolivia, Plurinational State of');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (535, 'BQ', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (76, 'BR', 'Brazil');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (44, 'BS', 'Bahamas');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (64, 'BT', 'Bhutan');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (74, 'BV', 'Bouvet Island');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (72, 'BW', 'Botswana');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (112, 'BY', 'Belarus');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (84, 'BZ', 'Belize');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (124, 'CA', 'Canada');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (166, 'CC', 'Cocos (Keeling) Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (180, 'CD', 'Congo, Democratic Republic of the');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (140, 'CF', 'Central African Republic');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (178, 'CG', 'Congo');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (756, 'CH', 'Switzerland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (384, 'CI', 'Côte d''Ivoire');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (184, 'CK', 'Cook Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (152, 'CL', 'Chile');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (120, 'CM', 'Cameroon');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (156, 'CN', 'China');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (170, 'CO', 'Colombia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (188, 'CR', 'Costa Rica');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (192, 'CU', 'Cuba');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (132, 'CV', 'Cabo Verde');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (531, 'CW', 'Curaçao');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (162, 'CX', 'Christmas Island');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (196, 'CY', 'Cyprus');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (203, 'CZ', 'Czechia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (276, 'DE', 'Germany');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (262, 'DJ', 'Djibouti');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (208, 'DK', 'Denmark');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (212, 'DM', 'Dominica');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (214, 'DO', 'Dominican Republic');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (12, 'DZ', 'Algeria');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (218, 'EC', 'Ecuador');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (233, 'EE', 'Estonia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (818, 'EG', 'Egypt');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (732, 'EH', 'Western Sahara');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (232, 'ER', 'Eritrea');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (724, 'ES', 'Spain');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (231, 'ET', 'Ethiopia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (246, 'FI', 'Finland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (242, 'FI', 'Fiji');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (238, 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (583, 'FM', 'Micronesia, Federated States of');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (234, 'FO', 'Faroe Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (250, 'FR', 'France');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (266, 'GA', 'Gabon');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (826, 'GB', 'United Kingdom of Great Britain and Northern Ireland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (308, 'GD', 'Grenada');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (268, 'GE', 'Georgia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (254, 'GF', 'French Guiana');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (831, 'GG', 'Guernsey');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (288, 'GH', 'Ghana');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (292, 'GI', 'Gibraltar');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (304, 'GL', 'Greenland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (270, 'GM', 'Gambia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (324, 'GN', 'Guinea');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (312, 'GP', 'Guadeloupe');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (226, 'GQ', 'Equatorial Guinea');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (300, 'GR', 'Greece');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (239, 'GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (320, 'GT', 'Guatemala');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (316, 'GU', 'Guam');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (624, 'GW', 'Guinea-Bissau');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (328, 'GY', 'Guyana');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (344, 'HK', 'Hong Kong');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (334, 'HM', 'Heard Island and McDonald Islands');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (340, 'HN', 'Honduras');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (191, 'HR', 'Croatia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (332, 'HT', 'Haiti');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (348, 'HU', 'Hungary');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (360, 'ID', 'Indonesia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (372, 'IE', 'Ireland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (376, 'IL', 'Israel');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (833, 'IM', 'Isle of Man');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (356, 'IN', 'India');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (86, 'IO', 'British Indian Ocean Territory');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (368, 'IQ', 'Iraq');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (364, 'IR', 'Iran, Islamic Republic of');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (352, 'IS', 'Iceland');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (380, 'IT', 'Italy');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (832, 'JE', 'Jersey');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (388, 'JM', 'Jamaica');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (400, 'JO', 'Jordan');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (392, 'JP', 'Japan');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (404, 'KE', 'Kenya');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (417, 'KG', 'Kyrgyzstan');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (116, 'KH', 'Cambodia');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (296, 'KI', 'Kiribati');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (174, 'KM', 'Comoros');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (659, 'KN', 'Saint Kitts and Nevis');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (408, 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (410, 'KR', 'Korea, Republic of');
INSERT INTO two-letter_country_codes(id, code, country) VALUES (414, 'KW', 'Kuwait');
